program RetroTune;

uses

  System.StartUpCopy,
  A2600.AudioMachine in '..\source\cores\a2600\A2600.AudioMachine.pas',
  A2600.Sound.TIA in '..\source\cores\a2600\A2600.Sound.TIA.pas',
  Amiga.AHX in '..\source\cores\amiga\Amiga.AHX.pas',
  DC.AudioMachine in '..\source\cores\dc\DC.AudioMachine.pas',
  DC.CPU.ARM7 in '..\source\cores\dc\DC.CPU.ARM7.pas',
  DC.Sound.AICA.DSP in '..\source\cores\dc\DC.Sound.AICA.DSP.pas',
  DC.Sound.AICA in '..\source\cores\dc\DC.Sound.AICA.pas',
  MSX.AudioMachine in '..\source\cores\msx\MSX.AudioMachine.pas',
  MSX.Sound.OPLL in '..\source\cores\msx\MSX.Sound.OPLL.pas',
  MSX.Sound.SCC in '..\source\cores\msx\MSX.Sound.SCC.pas',
  PCE.AudioMachine in '..\source\cores\pce\PCE.AudioMachine.pas',
  PCE.CPU in '..\source\cores\pce\PCE.CPU.pas',
  PCE.Sound.HuC6280 in '..\source\cores\pce\PCE.Sound.HuC6280.pas',
  SMS.Sound.SN76489 in '..\source\cores\sms\SMS.Sound.SN76489.pas',
  RetroTune.Decoder.TIA in 'decoders\RetroTune.Decoder.TIA.pas',
  RetroTune.Decoder.KSS in 'decoders\RetroTune.Decoder.KSS.pas',
  RetroTune.Decoder.HES in 'decoders\RetroTune.Decoder.HES.pas',
  RetroTune.Decoder.AHX in 'decoders\RetroTune.Decoder.AHX.pas',
  RetroTune.Decoder.DSF in 'decoders\RetroTune.Decoder.DSF.pas',
  RetroTune.Decoder.TRDOS in 'decoders\RetroTune.Decoder.TRDOS.pas',
  RetroTune.TIATracker in 'trackers\RetroTune.TIATracker.pas',
  FMX.Forms,
  C64.CPU in '..\source\cores\c64\C64.CPU.pas',
  C64.Sound.SID in '..\source\cores\c64\C64.Sound.SID.pas',
  C64.AudioMachine in '..\source\cores\c64\C64.AudioMachine.pas',
  ZX.AudioMachine in '..\source\cores\zx\ZX.AudioMachine.pas',
  ZX.Sound.YM2149 in '..\source\cores\zx\ZX.Sound.YM2149.pas',
  PC.OPL.Nuked in '..\source\cores\pc\PC.OPL.Nuked.pas',
  PC.Sound.OPL in '..\source\cores\pc\PC.Sound.OPL.pas',
  PC.Sound.OPL2 in '..\source\cores\pc\PC.Sound.OPL2.pas',
  PC.Sound.OPL3 in '..\source\cores\pc\PC.Sound.OPL3.pas',
  RetroTune.Main in 'ui\RetroTune.Main.pas' {FormMain},
  RetroTune.Decoder in 'decoders\RetroTune.Decoder.pas',
  RetroTune.Decoder.NSF in 'decoders\RetroTune.Decoder.NSF.pas',
  RetroTune.Decoder.NSFe in 'decoders\RetroTune.Decoder.NSFe.pas',
  RetroTune.Decoder.SPC in 'decoders\RetroTune.Decoder.SPC.pas',
  RetroTune.Decoder.GBS in 'decoders\RetroTune.Decoder.GBS.pas',
  RetroTune.Decoder.VGM in 'decoders\RetroTune.Decoder.VGM.pas',
  RetroTune.PT3.Engine in 'trackers\RetroTune.PT3.Engine.pas',
  RetroTune.ZXTracker.Engine in 'trackers\RetroTune.ZXTracker.Engine.pas',
  RetroTune.Decoder.ZXTrackers in 'decoders\RetroTune.Decoder.ZXTrackers.pas',
  RetroTune.Compression.LH5 in 'common\RetroTune.Compression.LH5.pas',
  RetroTune.Decoder.AYDumps in 'decoders\RetroTune.Decoder.AYDumps.pas',
  RetroTune.Decoder.Atari in 'decoders\RetroTune.Decoder.Atari.pas',
  Atari.Audio.ASAP in '..\source\cores\atari\Atari.Audio.ASAP.pas',
  Atari.Audio.MPT in '..\source\cores\atari\Atari.Audio.MPT.pas',
  Atari.AudioMachine in '..\source\cores\atari\Atari.AudioMachine.pas',

  RetroTune.Decoder.AY in 'decoders\RetroTune.Decoder.AY.pas',
  RetroTune.Decoder.SID in 'decoders\RetroTune.Decoder.SID.pas',
  RetroTune.Decoder.PT3 in 'decoders\RetroTune.Decoder.PT3.pas',
  RetroTune.Decoder.GYM in 'decoders\RetroTune.Decoder.GYM.pas',
  RetroTune.TFM.Stream in 'trackers\RetroTune.TFM.Stream.pas',
  RetroTune.TFM.MusicMaker in 'trackers\RetroTune.TFM.MusicMaker.pas',
  RetroTune.Decoder.TurboFM in 'decoders\RetroTune.Decoder.TurboFM.pas',
  RetroTune.VortexText in 'trackers\RetroTune.VortexText.pas',
  RetroTune.Decoder.Containers in 'decoders\RetroTune.Decoder.Containers.pas',
  ZX.Sound.YM2203 in '..\source\cores\zx\ZX.Sound.YM2203.pas',
  RetroTune.Digital.Module in 'trackers\RetroTune.Digital.Module.pas',
  RetroTune.Decoder.Digital in 'decoders\RetroTune.Decoder.Digital.pas',
  RetroTune.ETracker in 'trackers\RetroTune.ETracker.pas',
  RetroTune.Decoder.SAA in 'decoders\RetroTune.Decoder.SAA.pas',
  ZX.Sound.DAC in '..\source\cores\zx\ZX.Sound.DAC.pas',
  SAM.Sound.SAA1099 in '..\source\cores\sam\SAM.Sound.SAA1099.pas',
  RetroTune.Binary in 'common\RetroTune.Binary.pas',
  RetroTune.Player in 'playback\RetroTune.Player.pas',
  RetroTune.Export.WAV in 'export\RetroTune.Export.WAV.pas',
  RetroTune.Decoder.WAV in 'decoders\RetroTune.Decoder.WAV.pas',
  RetroTune.InfoForm in 'ui\RetroTune.InfoForm.pas',
  RetroTune.ReferenceForm in 'ui\RetroTune.ReferenceForm.pas',
  RetroTune.FormatsForm in 'ui\RetroTune.FormatsForm.pas',
  RetroTune.Chip.FDS in 'chips\RetroTune.Chip.FDS.pas',
  RetroTune.Spectrum in 'playback\RetroTune.Spectrum.pas';

{$R *.res}

begin
  Application.Initialize;
  Application.CreateForm(TFormMain, FormMain);
  Application.Run;
end.
