program RetroMul;

uses

  System.StartUpCopy,
  A2600.AudioMachine in '..\source\cores\a2600\A2600.AudioMachine.pas',
  A2600.Sound.TIA in '..\source\cores\a2600\A2600.Sound.TIA.pas',
  Amiga.AHX in '..\source\cores\amiga\Amiga.AHX.pas',
  Amiga.ProTracker in '..\source\cores\amiga\Amiga.ProTracker.pas',
  DC.AudioMachine in '..\source\cores\dc\DC.AudioMachine.pas',
  DC.CPU.ARM7 in '..\source\cores\dc\DC.CPU.ARM7.pas',
  DC.Sound.AICA.DSP in '..\source\cores\dc\DC.Sound.AICA.DSP.pas',
  DC.Sound.AICA in '..\source\cores\dc\DC.Sound.AICA.pas',
  MSX.AudioMachine in '..\source\cores\msx\MSX.AudioMachine.pas',
  MSX.Sound.OPLL in '..\source\cores\msx\MSX.Sound.OPLL.pas',
  MSX.Sound.SCC in '..\source\cores\msx\MSX.Sound.SCC.pas',
  PCE.AudioMachine in '..\source\cores\pce\PCE.AudioMachine.pas',
  PCE.CPU in '..\source\cores\pce\PCE.CPU.pas',
  PCE.Sound.HuC6280 in '..\source\cores\pce\PCE.Sound.HuC6280.pas',
  SMS.Sound.SN76489 in '..\source\cores\sms\SMS.Sound.SN76489.pas',
  FMX.Forms,
  C64.CPU in '..\source\cores\c64\C64.CPU.pas',
  C64.Sound.SID in '..\source\cores\c64\C64.Sound.SID.pas',
  C64.AudioMachine in '..\source\cores\c64\C64.AudioMachine.pas',
  Atari.Audio.ASAP in '..\source\cores\atari\Atari.Audio.ASAP.pas',
  Atari.Audio.MPT in '..\source\cores\atari\Atari.Audio.MPT.pas',
  Atari.AudioMachine in '..\source\cores\atari\Atari.AudioMachine.pas',
  ZX.AudioMachine in '..\source\cores\zx\ZX.AudioMachine.pas',
  ZX.Sound.YM2149 in '..\source\cores\zx\ZX.Sound.YM2149.pas',
  ZX.Sound.YM2203 in '..\source\cores\zx\ZX.Sound.YM2203.pas',
  ZX.Sound.DAC in '..\source\cores\zx\ZX.Sound.DAC.pas',
  SAM.Sound.SAA1099 in '..\source\cores\sam\SAM.Sound.SAA1099.pas',
  PC.OPL.Nuked in '..\source\cores\pc\PC.OPL.Nuked.pas',
  PC.Sound.OPL in '..\source\cores\pc\PC.Sound.OPL.pas',
  PC.Sound.OPL2 in '..\source\cores\pc\PC.Sound.OPL2.pas',
  PC.Sound.OPL3 in '..\source\cores\pc\PC.Sound.OPL3.pas',
  {$IFDEF ANDROID}
  FMX.Skia,
  {$ENDIF }
  FMX.Dialogs,
  FMX.OpenDialog in 'FMX.OpenDialog.pas',
  Core.Storage in '..\source\cores\Core.Storage.pas',
  Core.RomFormat in '..\source\cores\Core.RomFormat.pas',
  Core.RomHashes in '..\source\cores\Core.RomHashes.pas',
  RM.Storage.Dialogs in 'RM.Storage.Dialogs.pas',
  RM.Gamepad in 'devices\RM.Gamepad.pas',
  RM.TouchInput.Android in 'devices\RM.TouchInput.Android.pas',
  NES.SuborKeyboard in 'devices\NES.SuborKeyboard.pas',
  NES.FamicomKeyboard in 'devices\NES.FamicomKeyboard.pas',
  NES.MiraclePiano in 'devices\NES.MiraclePiano.pas',
  NES.MiraclePianoDevice in '..\source\cores\nes\NES.MiraclePianoDevice.pas',
  NES.FamicomKeyboardDevice in '..\source\cores\nes\NES.FamicomKeyboardDevice.pas',
  NES.FamicomDataRecorder in '..\source\cores\nes\NES.FamicomDataRecorder.pas',
  NES.PowerPad in 'devices\NES.PowerPad.pas',
  NES.DataRecorder in 'devices\NES.DataRecorder.pas',
  RM.Main in 'RM.Main.pas' {FormMain},
  RM.FrameUpload in 'RM.FrameUpload.pas',
  RM.Input in 'RM.Input.pas',
  RM.Settings in 'RM.Settings.pas',
  Core.InputConfig in '..\source\cores\Core.InputConfig.pas',
  FMXInput in '..\source\input\FMXInput.pas',
  {$IFDEF ANDROID}
  RM.DocumentTransfer.Android in 'RM.DocumentTransfer.Android.pas',
  Core.Storage.Android in '..\source\cores\Core.Storage.Android.pas',
  {$ENDIF }
  {$IF Defined(ANDROID) and not Defined(PCM_AUDIO_NULL)}
  PCM.Audio.Android.AudioTrack in '..\source\PCM\PCM.Audio.Android.AudioTrack.pas',
  {$ENDIF }
  {$IF Defined(MSWINDOWS)}
  FMX.Platform.Win in 'DelphiWinUI3\Fixes\D13\FMX.Platform.Win.pas',
  {$ENDIF }
  {$IF Defined(MSWINDOWS) and not Defined(PCM_AUDIO_NULL)}
  PCM.Audio.Windows.MMSystem in '..\source\PCM\PCM.Audio.Windows.MMSystem.pas',
  {$ENDIF }
  {$IF Defined(LINUX) and not Defined(ANDROID) and not Defined(PCM_AUDIO_NULL)}
  PCM.Audio.Linux.Alsa in '..\source\PCM\PCM.Audio.Linux.Alsa.pas',
  {$ENDIF }
  {$IF (Defined(MACOS) or Defined(IOS)) and not Defined(PCM_AUDIO_NULL)}
  PCM.Audio.Apple.AudioQueue in '..\source\PCM\PCM.Audio.Apple.AudioQueue.pas',
  {$ENDIF }
  PCM.Audio.Null in '..\source\PCM\PCM.Audio.Null.pas',
  PCM.Audio.Factory in '..\source\PCM\PCM.Audio.Factory.pas',
  Core.Snapshots in '..\source\cores\Core.Snapshots.pas',
  Core.AudioFilter in '..\source\cores\Core.AudioFilter.pas',
  PCM.Audio in '..\source\PCM\PCM.Audio.pas',
  PCM.Audio.Backend in '..\source\PCM\PCM.Audio.Backend.pas',
  Core.PerformanceHints in '..\source\cores\Core.PerformanceHints.pas',
  Core.Emulation in '..\source\cores\Core.Emulation.pas',
  Core.EmulatorFactory in '..\source\cores\Core.EmulatorFactory.pas',
  Core.Adapter.NES in '..\source\cores\Core.Adapter.NES.pas',
  Core.Adapter.GB in '..\source\cores\Core.Adapter.GB.pas',
  Core.Adapter.GBC in '..\source\cores\Core.Adapter.GBC.pas',
  Core.Adapter.NeoGeo in '..\source\cores\Core.Adapter.NeoGeo.pas',
  NeoGeo.Cartridge in '..\source\cores\neogeo\NeoGeo.Cartridge.pas',
  NeoGeo.Protection in '..\source\cores\neogeo\NeoGeo.Protection.pas',
  NeoGeo.Bootleg in '..\source\cores\neogeo\NeoGeo.Bootleg.pas',
  NeoGeo.PCB in '..\source\cores\neogeo\NeoGeo.PCB.pas',
  NeoGeo.RomSets in '..\source\cores\neogeo\NeoGeo.RomSets.pas',
  NeoGeo.Video in '..\source\cores\neogeo\NeoGeo.Video.pas',
  NeoGeo.Sound in '..\source\cores\neogeo\NeoGeo.Sound.pas',
  NeoGeo.Console in '..\source\cores\neogeo\NeoGeo.Console.pas',
  NeoGeo.Emulation in '..\source\cores\neogeo\NeoGeo.Emulation.pas',
  Core.Adapter.MD in '..\source\cores\Core.Adapter.MD.pas',
  Core.Adapter.SNES in '..\source\cores\Core.Adapter.SNES.pas',
  SNES.Cartridge in '..\source\cores\snes\SNES.Cartridge.pas',
  SNES.SDD1 in '..\source\cores\snes\SNES.SDD1.pas',
  SNES.NecDSP in '..\source\cores\snes\SNES.NecDSP.pas',
  SNES.CX4 in '..\source\cores\snes\SNES.CX4.pas',
  SNES.SA1 in '..\source\cores\snes\SNES.SA1.pas',
  SNES.GSU in '..\source\cores\snes\SNES.GSU.pas',
  SNES.SPC7110 in '..\source\cores\snes\SNES.SPC7110.pas',
  SNES.ST018 in '..\source\cores\snes\SNES.ST018.pas',
  SNES.CPU in '..\source\cores\snes\SNES.CPU.pas',
  SNES.PPU in '..\source\cores\snes\SNES.PPU.pas',
  SNES.SPC in '..\source\cores\snes\SNES.SPC.pas',
  SNES.Console in '..\source\cores\snes\SNES.Console.pas',
  SNES.Emulation in '..\source\cores\snes\SNES.Emulation.pas',
  MD.Arithmetic in '..\source\cores\md\MD.Arithmetic.pas',
  MD.Cartridge in '..\source\cores\md\MD.Cartridge.pas',
  MD.Console in '..\source\cores\md\MD.Console.pas',
  MD.M68k in '..\source\cores\md\MD.M68k.pas',
  MD.Z80 in '..\source\cores\md\MD.Z80.pas',
  MD.VDP in '..\source\cores\md\MD.VDP.pas',
  MD.Sound in '..\source\cores\md\MD.Sound.pas',
  NES.Mapper in '..\source\cores\nes\NES.Mapper.pas',
  NES.Mapper.Factory in '..\source\cores\nes\NES.Mapper.Factory.pas',
  NES.Mapper.ColorDreams in '..\source\cores\nes\mappers\NES.Mapper.ColorDreams.pas',
  NES.Mapper.Banked in '..\source\cores\nes\mappers\NES.Mapper.Banked.pas',
  NES.Mapper.Discrete in '..\source\cores\nes\mappers\NES.Mapper.Discrete.pas',
  NES.Mapper.MmcLatch in '..\source\cores\nes\mappers\NES.Mapper.MmcLatch.pas',
  NES.Mapper.Mmc3Variants in '..\source\cores\nes\mappers\NES.Mapper.Mmc3Variants.pas',
  NES.Mapper.Vrc in '..\source\cores\nes\mappers\NES.Mapper.Vrc.pas',
  NES.Mapper.Sunsoft in '..\source\cores\nes\mappers\NES.Mapper.Sunsoft.pas',
  NES.Mapper.Rambo in '..\source\cores\nes\mappers\NES.Mapper.Rambo.pas',
  NES.Mapper.Cony in '..\source\cores\nes\mappers\NES.Mapper.Cony.pas',
  NES.Mapper.Bandai in '..\source\cores\nes\mappers\NES.Mapper.Bandai.pas',
  NES.Mapper.Jy in '..\source\cores\nes\mappers\NES.Mapper.Jy.pas',
  NES.Mapper.Mmc5 in '..\source\cores\nes\mappers\NES.Mapper.Mmc5.pas',
  NES.Mapper.Subor in '..\source\cores\nes\mappers\NES.Mapper.Subor.pas',
  NES.Mapper.Warface in '..\source\cores\nes\mappers\NES.Mapper.Warface.pas',
  NES.Mapper.Drip in '..\source\cores\nes\mappers\NES.Mapper.Drip.pas',
  NES.Mapper.ExtendedDiscrete in '..\source\cores\nes\mappers\NES.Mapper.ExtendedDiscrete.pas',
  NES.Mapper.ExtendedIrq in '..\source\cores\nes\mappers\NES.Mapper.ExtendedIrq.pas',
  NES.Mapper.ExtendedMemory in '..\source\cores\nes\mappers\NES.Mapper.ExtendedMemory.pas',
  NES.Mapper.ExtendedMmc3 in '..\source\cores\nes\mappers\NES.Mapper.ExtendedMmc3.pas',
  NES.Mapper.Flash in '..\source\cores\nes\mappers\NES.Mapper.Flash.pas',
  NES.Mapper.Multicart in '..\source\cores\nes\mappers\NES.Mapper.Multicart.pas',
  NES.Mapper.Namco in '..\source\cores\nes\mappers\NES.Mapper.Namco.pas',
  NES.Mapper.Rainbow in '..\source\cores\nes\mappers\NES.Mapper.Rainbow.pas',
  NES.Mapper.Sachen in '..\source\cores\nes\mappers\NES.Mapper.Sachen.pas',
  NES.Mapper.VrcAudio in '..\source\cores\nes\mappers\NES.Mapper.VrcAudio.pas',
  NES.Mapper.Mmc1 in '..\source\cores\nes\mappers\NES.Mapper.Mmc1.pas',
  NES.Mapper.Mmc3 in '..\source\cores\nes\mappers\NES.Mapper.Mmc3.pas',
  NES.Mapper.Nrom in '..\source\cores\nes\mappers\NES.Mapper.Nrom.pas',
  NES.Mapper.Uxrom in '..\source\cores\nes\mappers\NES.Mapper.Uxrom.pas',
  NES.Mapper.Axrom in '..\source\cores\nes\mappers\NES.Mapper.Axrom.pas',
  NES.Mapper.Cnrom in '..\source\cores\nes\mappers\NES.Mapper.Cnrom.pas',
  NES.Mapper.Gxrom in '..\source\cores\nes\mappers\NES.Mapper.Gxrom.pas',
  NES.PPU in '..\source\cores\nes\NES.PPU.pas',
  NES.State in '..\source\cores\nes\NES.State.pas',
  NES.Types in '..\source\cores\nes\NES.Types.pas',
  NES.APU in '..\source\cores\nes\NES.APU.pas',
  NES.AudioDiagnostics in '..\source\cores\nes\NES.AudioDiagnostics.pas',
  NES.Emulation in '..\source\cores\nes\NES.Emulation.pas',
  NES.Bus in '..\source\cores\nes\NES.Bus.pas',
  NES.Cartridge in '..\source\cores\nes\NES.Cartridge.pas',
  NES.RomMetadata in '..\source\cores\nes\NES.RomMetadata.pas',
  NES.Console in '..\source\cores\nes\NES.Console.pas',
  NES.Consts in '..\source\cores\nes\NES.Consts.pas',
  NES.Controller in '..\source\cores\nes\NES.Controller.pas',
  NES.Input in '..\source\cores\nes\NES.Input.pas',
  NES.CPU in '..\source\cores\nes\NES.CPU.pas',
  GB.Cartridge in '..\source\cores\gb\GB.Cartridge.pas',
  GB.CPU in '..\source\cores\gb\GB.CPU.pas',
  GB.EmulationThread in '..\source\cores\gb\GB.EmulationThread.pas',
  GB.GPU in '..\source\cores\gb\GB.GPU.pas',
  GB.InterruptManager in '..\source\cores\gb\GB.InterruptManager.pas',
  GB.Joypad in '..\source\cores\gb\GB.Joypad.pas',
  GB.MBC in '..\source\cores\gb\GB.MBC.pas',
  GB.Camera in '..\source\cores\gb\GB.Camera.pas',
  RM.Camera.Bitmap in 'RM.Camera.Bitmap.pas',
  GB.Memory in '..\source\cores\gb\GB.Memory.pas',
  GB.Palettes in '..\source\cores\gb\GB.Palettes.pas',
  GB.ROM in '..\source\cores\gb\GB.ROM.pas',
  GB.Sound.Channel in '..\source\cores\gb\GB.Sound.Channel.pas',
  GB.Sound in '..\source\cores\gb\GB.Sound.pas',
  GB.Timer in '..\source\cores\gb\GB.Timer.pas',
  GBC.Cartridge in '..\source\cores\gbc\GBC.Cartridge.pas',
  GBC.CPU in '..\source\cores\gbc\GBC.CPU.pas',
  GBC.EmulationThread in '..\source\cores\gbc\GBC.EmulationThread.pas',
  GBC.GPU in '..\source\cores\gbc\GBC.GPU.pas',
  GBC.InterruptManager in '..\source\cores\gbc\GBC.InterruptManager.pas',
  GBC.Joypad in '..\source\cores\gbc\GBC.Joypad.pas',
  GBC.MBC in '..\source\cores\gbc\GBC.MBC.pas',
  GBC.Memory in '..\source\cores\gbc\GBC.Memory.pas',
  GBC.ROM in '..\source\cores\gbc\GBC.ROM.pas',
  GBC.Sound.Channel in '..\source\cores\gbc\GBC.Sound.Channel.pas',
  GBC.Sound in '..\source\cores\gbc\GBC.Sound.pas',
  GBC.Timer in '..\source\cores\gbc\GBC.Timer.pas',
  SCRP.GameList in '..\source\gamelist\SCRP.GameList.pas',
  RM.Styles in 'RM.Styles.pas' {FormStyles},
  FMX.Menus in 'DelphiWinUI3\Fixes\D13\FMX.Menus.pas',
  FMX.StyledContextMenu in 'DelphiWinUI3\Fixes\D13\FMX.StyledContextMenu.pas',
  FMX.Windows.Hints in 'DelphiWinUI3\FMXWindowsHint\FMX.Windows.Hints.pas',
  HGM.FMX.Image in 'HGM.FMX.Image.pas',
  Core.SavePaths in '..\source\cores\Core.SavePaths.pas',
  MD.Emulation in '..\source\cores\md\MD.Emulation.pas';

{$R *.res}

begin
  {$IFDEF ANDROID}
  GlobalUseSkia := True;
  {$ENDIF}
  Application.Initialize;
  Application.CreateForm(TFormMain, FormMain);
  Application.Run;
end.

